name: rsync-deploy-action tester

on:
  push:
    branches: [master]

jobs:
  hello_world_rsync_deploy:
    runs-on: ubuntu-latest
    name: A job to test rsync-deploy-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Modify files permissions
        run: |
          chmod 777 -R ./
          ls -l
      - name: Tester
        uses: yeshan333/rsync-deploy-action@main
        id: rsync-deploy-action
        with:
          ssh_login_username: geoff@geoffgraham.me
          remote_server_ip: ${{ secrets.SERVER_IP }}
          ssh_port: ${{ secrets.FTP_PORT }}
          ssh_private_key: ${{ secrets.SERVER_SSH }}
          source_path: ./*
          destination_path: ${{ secrets.FTP_DIRECTORY }}