name: Deploy Website
on: [push]
jobs:  
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: deploy website to example.com
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.FTP_PASSWORD }}
        with:
          source: "/*"
          target: "/domains/geoffgraham.me/html/wp-content/themes/v02"
          strip_components: 1


on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: s218813.gridserver.com/domains/geoffgraham.me/html/wp-content/themes/v02
        ftp-username: geoffgraham.me
        ftp-password: ${{ secrets.FTP_PASSWORD }}