name: Publish Website

on: push

jobs:
  Fast-FTP-Action:
    name: Fast FTP Action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fast FTP Action
      uses: anvil-solutions/Fast-FTP-Action@2.1.0
      with:
        server: sftp.flywheelsites.com
        username: myFtpUserName
        password: ${{ secrets.FTP_PASSWORD }}