# Workflow name
name: Deploy site to live
 
on:
  # Run automatically on push to main branch
  push:
    branches: [ master ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get files
      uses: actions/checkout@v2.3.4
      
    - name: FTP Deploy
      uses: cinderblockgames/ftp-action@v1.2.2
      with:
        # required
        server: sftp.flywheelsites.com
        username: geoffgraham
        password: ${{ secrets.FTP_PASSWORD }}
        # optional
        port: 22
        destination: wp-content/themes/
        skipUnchanged: true
        skipDirectories: .github|.well-known|configs|private-keys
        test: true