name: 🚀 Deploy website on push
on: [ push ]
permissions: write-all
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD}}
        port: 22
        protocol: ftps-legacy
        server-dir: ${{ secrets.FTP_DIRECTORY}}
        exclude: .git*
          - .git*/**
          -  **/.git*/**
          - node_modules/**
          - node_modules/**/*
